In [ ]:
%load_ext autoreload
%autoreload 2

In [25]:
import os
from pathlib import Path
import sys
from typing import Optional, List, Dict, Any, Tuple
if '..' not in sys.path: sys.path.append('..')

from dataclasses import dataclass
from datasets import load_dataset
from datasets.arrow_dataset import Dataset
import numpy as np
from matplotlib import pyplot as plt
from pydantic_yaml import parse_yaml_file_as
import torch
from torch import nn, dist
import torch.nn.functional as F
from transformers import GPT2Tokenizer, AddedToken, PreTrainedTokenizer, AutoTokenizer, BatchEncoding

from mllm.data.wiki.dswiki import WikiDsLoader
from mllm.data.utils import RandomInputTokenizer, RandomInputTokenizerV2, TokensSubset, TokensSubsetV2, tokens_subsets_to_tensors, tokens_subsets_v2_to_tensors
from mllm.exp.args import ENCDEC_GRAPH_BERT_MODEL_CFG_FNAME
from mllm.model.encdec_ranker_hg import EncdecGraphBert
from mllm.config.model import EncdecGraphBertCfg
from mllm.train.encdec_graph_bert import MaskedCiteDataset, create_masked_cite_dataloader, load_split_wiki_dataset



In [32]:
# DATA_PATH = Path(os.path.expandvars('$HOME')) / 'data'
DATA_PATH = Path('Q:/data')
# WIKI_DS_NAME = '20200501.en'
WIKI_DS_NAME = '20220301.en'

TRAIN_ENCDEC_GRAPH_BERT_PATH = DATA_PATH / 'train_mllm_encdec_bert'
encdec_subdir = 'encdecgraphbert-20260213_121906'

encdec_train_path = TRAIN_ENCDEC_GRAPH_BERT_PATH / encdec_subdir
encdec_snapshot_fpath = encdec_train_path / 'best.pth'
encdec_graph_model_cfg_fpath = encdec_train_path / ENCDEC_GRAPH_BERT_MODEL_CFG_FNAME

device_name = 'cpu'
# device_name = 'cuda'

device = torch.device(device_name)
print(device)

cpu


## Wikipeida dataset loading

In [27]:
# dss = load_dataset('wikipedia', WIKI_DS_NAME, beam_runner='DirectRunner', cache_dir=str(DATA_PATH))
dss = load_dataset('wikipedia', WIKI_DS_NAME, cache_dir=str(DATA_PATH), trust_remote_code=True)
ds: Dataset = dss['train']
n_docs = len(ds)
print(f'Wikipedia {WIKI_DS_NAME} docs: {n_docs}')

Loading dataset shards:   0%|          | 0/41 [00:00<?, ?it/s]

Wikipedia 20220301.en docs: 6458670


### Masked dataset loading

In [28]:
tkz = AutoTokenizer.from_pretrained('bert-base-uncased')
inp_len = 128
n_special_toks = 3
mask_cfg = None
ds_cite = MaskedCiteDataset(ds, tkz, max_seq_len=inp_len, n_special_toks=n_special_toks, mask_cfg=mask_cfg, device=device)

### Inspect a masked dataset batch samples

In [6]:
batch_size = 5
inds = np.arange(batch_size)
inds = inds.tolist()
batch = ds_cite.get_batch(inds)

Token indices sequence length is longer than the specified maximum sequence length for this model (8349 > 512). Running this sequence through the model will result in indexing errors


In [7]:
print(tkz)

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


In [8]:
print(f'inp_toks: {batch.inp_toks.shape}. inp_attn_mask: {batch.inp_att_mask.shape}. first: {batch.inp_toks[0, 0]}. last: {batch.inp_toks[0, -1]}.')
print(f'prompts_toks: {batch.prompts_toks.shape}. prompts_attn_mask: {batch.prompts_att_mask.shape}. first: {batch.prompts_toks[0, 0]}. last: {batch.prompts_toks[0, -1]}.')


inp_toks: torch.Size([5, 128]). inp_attn_mask: torch.Size([5, 128]). first: 101. last: 102.
prompts_toks: torch.Size([5, 27]). prompts_attn_mask: torch.Size([5, 27]). first: 21893. last: 1012.


In [9]:
print(tkz.decode(batch.inp_toks[0].cpu().numpy()))
print(batch.inp_toks[0])

[CLS] between the two. anarchist tactics have shifted during the course of the last century. anarchists during the early 20th century focused more on strikes and militancy while contemporary anarchists use a broader array of approaches. classical era tactics discreet chandlerzzy during the classical era, anarchists had a militant tendency. not only did they confront state armed forces, as in spain and ukraine, but some of them also employed terrorism as propaganda of the deed. assassination attempts were carried out against heads of state, some oswald suspicious turns of which were successful. anarchists also took part in revolutions. many anarchists, especially the galleanists, believed [SEP]
tensor([  101,  2090,  1996,  2048,  1012, 18448,  9887,  2031,  5429,  2076,
         1996,  2607,  1997,  1996,  2197,  2301,  1012, 18448,  2015,  2076,
         1996,  2220,  3983,  2301,  4208,  2062,  2006,  9326,  1998, 23689,
        25451,  5666,  2096,  3824, 18448,  2015,  2224,  1037,

In [22]:
print(torch.all(batch.inp_toks == batch.inp_masked_toks))

tensor(True)


In [10]:
print(tkz.decode(batch.prompts_toks[0].cpu().numpy()))
print(batch.prompts_toks[0])

cite tag begin : " discreet chandlerzzy ". cite tag end : " oswald suspicious turns ". produce whole text containing these tags.
tensor([21893,  6415,  4088,  1024,  1000, 29321, 13814, 28753,  1000,  1012,
        21893,  6415,  2203,  1024,  1000, 17411, 10027,  4332,  1000,  1012,
         3965,  2878,  3793,  4820,  2122, 22073,  1012])


In [12]:
print(batch.cites_toks[0])

tensor([ 2076,  1996,  4556,  3690,  1010, 18448,  2015,  2018,  1037, 16830,
        11765,  1012,  2025,  2069,  2106,  2027, 14323,  2110,  4273,  2749,
         1010,  2004,  1999,  3577,  1998,  5924,  1010,  2021,  2070,  1997,
         2068,  2036,  4846, 10130,  2004, 10398,  1997,  1996, 15046,  1012,
        10102,  4740,  2020,  3344,  2041,  2114,  4641,  1997,  2110,  1010,
         2070,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0])


## Model loading and inference

In [37]:
model_cfg = parse_yaml_file_as(EncdecGraphBertCfg, encdec_graph_model_cfg_fpath)
chkpt = torch.load(encdec_snapshot_fpath, map_location=device)
model = EncdecGraphBert(model_cfg, tkz).to(device)
strict = True
# strict = False
model.load_pretrained(chkpt)
del chkpt
model.eval()
None

### Inference

In [39]:
batch_off = 0
batch_size = 5
inds = np.arange(batch_size) + batch_off
inds = inds.tolist()
batch = ds_cite.get_batch(inds)

In [41]:
loss_dict, dec_logits = model.run_on_text_citation(batch)
print(loss_dict)

{'cite_loss': tensor([4.6705], grad_fn=<MulBackward0>), 'cite_reg_toks_loss': tensor([5.1376], grad_fn=<MulBackward0>), 'cite_spc_toks_loss': tensor([0.0001], grad_fn=<MulBackward0>), 'emb_loss': tensor(0.0726, grad_fn=<MulBackward0>), 'emb_cos_loss': tensor(0.0178, grad_fn=<MeanBackward0>), 'emb_lr2_loss': tensor(0.1274, grad_fn=<MeanBackward0>), 'input_loss': tensor([0.4396], grad_fn=<MulBackward0>), 'input_reg_toks_loss': tensor([0.4836], grad_fn=<MulBackward0>), 'input_spc_toks_loss': tensor([2.4438e-06], grad_fn=<MulBackward0>), 'loss': tensor([1.7276], grad_fn=<DivBackward0>)}


In [43]:
logits = dec_logits.detach().numpy()
logits.shape

(5, 128, 30522)

In [46]:
probs_pred = torch.softmax(dec_logits, dim=-1)
print(probs_pred.shape)
docs_toks_out = torch.argmax(probs_pred, dim=-1)
docs_toks_out = docs_toks_out.detach().numpy()
print(docs_toks_out.shape)

torch.Size([5, 128, 30522])
(5, 128)


In [49]:
for i in range(batch_size):
    print(f'=== {i} ===')
    print('inp:')
    print(tkz.decode(batch.inp_toks[i].cpu().numpy()))
    print('prompts:')
    print(tkz.decode(batch.prompts_toks[i].cpu().numpy()))
    print('pred:')
    print(tkz.decode(docs_toks_out[i]))

=== 0 ===
inp:
[CLS] they would benefit predatory men. a historical current that arose and flourished during 1890 and 1920 within anarchism was stump gradually [unused565] free love. in contemporary anarchism, this current survives as a tendency to support polyamory and queer anarchism. free love advocates were against marriage, which they saw as a way of men imposing authority over women, largely because marriage law greatly favoured the power of men. the notion of free love was much broader and included a critique of the established order that limited women ' s sexual freedom and pleasure. those free love movements contributed to the establishment of communal義ヘ spoke houses, where large groups [SEP]
prompts:
[CLS] cite tag begin : " stump gradually [unused565] ". cite tag end : "義ヘ spoke ". produce whole text containing these tags. [SEP]
pred:
[CLS] not not as a sex.. a is is, in the,, of the, wasstead. further have by the other -. different social of sexualism.,, are in a sense of a

In [85]:
inp_len = model_cfg.enc_bert.inp_len
print('inp_len:', inp_len)

def get_batch_tokens(doc_inds: list[int], randomize: bool = False, mask_toks_len_max: int = 5) -> torch.Tensor:
    docs_toks = np.full((len(doc_inds), inp_len), tkz.pad_token_id)
    for i, doc_ind in enumerate(doc_inds):
        doc = ds[doc_ind]
        title, text = doc['title'], doc['text']
        doc_txt = f'{title} {text}'
        doc_txt = text
        doc_txt = doc_txt.lower()
        doc_toks: list[int] | np.ndarray = tkz(doc_txt)['input_ids']
        n_toks = len(doc_toks)
        if n_toks > inp_len:
            i_off = np.random.randint(1, n_toks - inp_len + 1) if randomize else 1
            doc_toks = np.concatenate([doc_toks[:1], doc_toks[i_off:i_off + inp_len - 2], doc_toks[-1:]])
            # print(doc_toks)

        mask_toks_len = np.random.randint(1, mask_toks_len_max + 1)
        mask_toks_off = np.random.randint(len(doc_toks) - mask_toks_len + 1)
        masked_toks = doc_toks[mask_toks_off:mask_toks_off + mask_toks_len]
        masked_substr = tkz.decode(masked_toks)
        print(f'{doc_ind:03d}. {masked_substr}')
        doc_toks[mask_toks_off:mask_toks_off + mask_toks_len] = tkz.mask_token_id

        docs_toks[i, :len(doc_toks)] = doc_toks
    docs_toks_t = torch.from_numpy(docs_toks).to(device)
    return docs_toks_t


inp_len: 128


In [86]:
doc_inds = np.arange(5)
# doc_inds += 5
doc_inds = [x.item() for x in doc_inds]
for doc_ind in doc_inds:
    doc = ds[doc_ind]
    title, text = doc['title'], doc['text'].replace('\n', '\\n')
    print(f'{doc_ind:03d} "{title}" {text[:400]}')

000 "Anarchism" Anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. As a historically left-wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian
001 "Autism" Autism is a neurodevelopmental disorder characterized by difficulties with social interaction and communication, and by restricted and repetitive behavior. Parents often notice signs during the first three years of their child's life. These signs often develop gradually, though some autistic children experience regression in their communication and social skills after reaching developmental milest
002 "Albedo" Albedo (; ) is the measure of the diffuse reflection of solar radiation out of the total solar radiation and measured on a scale from 0, corresponding to a 

In [92]:
docs_toks_in = get_batch_tokens(doc_inds)
print(docs_toks_in[0])
print(docs_toks_in.shape)
logits_pred = model(docs_toks_in, docs_toks_in != tkz.pad_token_id)
probs_pred = torch.softmax(logits_pred, dim=-1)
# probs_pred = torch.sigmoid(logits_pred)
print(probs_pred.shape)
docs_toks_out = torch.argmax(probs_pred, dim=-1)
print(docs_toks_out.shape)

000. formal hierarch
001. first
002. albedo (
003. written
004. yellowhammer state,
tensor([  101,  9617, 11140,  2964,  2003,  1037,  2576,  4695,  1998,  2929,
         2008,  2003,  8040, 23606,  7476,  1997,  3691,  1998, 19164,  2035,
        26097,  1010, 24873, 11890,  3512,  3596,  1997, 12571,  1012,  9617,
        11140,  2964,  4455,  2005,  1996, 15766,  1997,  1996,  2110,  1010,
         2029,  2009,  4324,  2000,  2022, 14203,  1010,  6151,  2229,  7895,
         3468,  1010,  1998, 17631,  1012,  2004,  1037,  7145,  2187,  1011,
         3358,  2929,  1010,  2872,  2006,  1996,  2521, 20515,  2187,  1997,
         1996,  2576,  8674,  1010,  2009,  2003,  2788,  2649,  4077, 15029,
         2964,  1998, 19297, 27255,  2004,  1996, 19297,  3358,  1006, 19297,
        14649,  1007,  1997,  1996,  6102,  2929,  1010,  1998,  2038,  1037,
         2844,  3439,  2523,  2007,  3424,  1011, 16498,  1998, 14649,  1012,
         4286,  2973,  1999,  8384,  2302,   103,   103,  

In [93]:
for i, doc_ind in enumerate(doc_inds):
    s = tkz.decode(docs_toks_in[i])
    s = s.replace('\n', '\\n')
    print(f'{doc_ind:03d} {s}')

000 [CLS] anarchism is a political philosophy and movement that is sceptical of authority and rejects all involuntary, coercive forms of hierarchy. anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful. as a historically left - wing movement, placed on the farthest left of the political spectrum, it is usually described alongside communalism and libertarian marxism as the libertarian wing ( libertarian socialism ) of the socialist movement, and has a strong historical association with anti - capitalism and socialism. humans lived in societies without [MASK] [MASK] [MASK] [MASK]ies long before the establishment of formal states [SEP]
001 [CLS] autism is a neurodevelopmental disorder characterized by difficulties with social interaction and communication, and by restricted and repetitive behavior. parents often notice signs during the [MASK] three years of their child ' s life. these signs often develop gradually, though some autistic 

In [94]:
for i, doc_ind in enumerate(doc_inds):
    s = tkz.decode(docs_toks_out[i])
    s = s.replace('\n', '\\n')
    print(f'{doc_ind:03d} {s}')

000 the, andrel [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
001 past two [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]

## Encoder embedding evaluation

In [16]:
def get_tokens(txts: list[str]) -> torch.Tensor:
    batch_toks = np.full((len(txts), inp_len), tkz.pad_token_id)
    for i, txt in enumerate(txts):
        toks: list[int] = tkz(txt)['input_ids']
        n_toks = len(toks)
        if n_toks > inp_len:
            i_off = np.random.randint(n_toks - inp_len + 1)
            toks = toks[i_off:i_off + inp_len]
        batch_toks[i, :len(toks)] = toks
    batch_toks_t = torch.from_numpy(batch_toks).to(device)
    return batch_toks_t

model.eval()
None

In [17]:
txts = [
    '"Orana Australia Ltd" Orana Australia Ltd is a not-for-profit organisation that provides a diverse range of training and support services to over 650 people with disabilities and their families in South Australia.\n\nHistory\nThe Mentally Retarded Children’s Society of SA Inc. was established in 1950 by a group of parent',
    'Australia',
    'Orana Australia Ltd',
    'Hello Kitty',
]
batch_toks = get_tokens(txts)
embs = model.enc_bert(batch_toks, batch_toks != tkz.pad_token_id)
# embs = embs.detach().cpu().numpy()
embs = embs.detach().cpu()
print(embs.shape)

torch.Size([4, 768])


In [18]:
for i in range(1, len(embs)):
    cos_dist = F.cosine_similarity(embs[0:1], embs[i:i + 1])
    norm_dist = torch.norm(embs[0] - embs[i])
    print(txts[i], cos_dist.numpy(), norm_dist)

Australia [0.1348315] tensor(9.7678)
Orana Australia Ltd [0.14778207] tensor(10.4330)
Hello Kitty [0.08750954] tensor(10.7561)


## Answering questions

In [40]:
ctx = 'Context3. Like other American research universities, Northwestern was transformed by World War II. Franklyn B. Snyder led the university from 1939 to 1949, when nearly 50,000 military officers and personnel were trained on the Evanston and Chicago campuses. After the war, surging enrollments under the G.I. Bill drove drastic expansion of both campuses. In 1948 prominent anthropologist Melville J. '
q = 'Question: Between 1939 and 1949, how many military officers and personnel were trained on the Evanston and Chicago campuses? Answer: [MASK] [MASK] [MASK] [MASK]'
s = f'{ctx} {q}'
toks = tkz(s).input_ids
len(toks)

109

In [41]:
toks_in = torch.tensor(toks).to(device).unsqueeze(0)
logits_pred = model(toks_in, toks_in != tkz.pad_token_id)
print(logits_pred.shape)
probs_pred = torch.softmax(logits_pred[0], dim=-1)
toks_out = torch.argmax(probs_pred, dim=-1)
toks_out

torch.Size([1, 128, 30522])


tensor([  101,  6123,  2509,  1012,  2066,  2060,  2137,  2470,  5534,  1010,
         7855,  2001,  8590,  2011,  2088,  2162,  2462,  1012, 19597,  2078,
         1038,  1012, 17840,  2419,  1996,  2118,  2013,  3912,  2000,  4085,
         1010,  2043,  3053,  2753,  1010,  2199,  2510,  3738,  1998,  5073,
         2020,  4738,  2006,  1996,  6473,  2669,  1998,  3190, 13696,  1012,
         2044,  1996,  2162,  1010,  7505,  4726, 10316,  2015,  2104,  1996,
         1043,  1012,  1045,  1012,  3021,  6303, 20851,  4935,  1997,  2119,
        13696,  1012,  1999,  3882,  4069, 21571, 20154,  1046,  1012,  3160,
         1024,  2090,  3912,  1998,  4085,  1010,  2129,  2116,  2510,  3738,
         1998,  5073,  2020,  4738,  2006,  1996,  6473,  2669,  1998,  3190,
        13696,  1029,  3437,  1024,  1000,  1024,  2137,  2015,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0])

In [42]:
tkz.decode(toks_out)

'[CLS] context3. like other american research universities, northwestern was transformed by world war ii. franklyn b. snyder led the university from 1939 to 1949, when nearly 50, 000 military officers and personnel were trained on the evanston and chicago campuses. after the war, surging enrollments under the g. i. bill demanded ample expansion of both campuses. in 1948 prominent anthropologist melville j. question : between 1939 and 1949, how many military officers and personnel were trained on the evanston and chicago campuses? answer : " : americans [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]'

In [34]:
probs_pred[:10]

tensor([1.0000e+00, 1.1139e-12, 6.2658e-13, 1.4770e-12, 1.5230e-12, 1.4352e-12,
        1.0220e-12, 1.1165e-12, 1.0452e-12, 1.1000e-12],
       grad_fn=<SliceBackward0>)

In [31]:
probs_pred.shape

torch.Size([5, 128, 30522])

In [19]:
t = torch.rand(2, 3, 4)
t

tensor([[[0.6792, 0.0907, 0.6140, 0.9981],
         [0.2409, 0.8605, 0.0702, 0.2925],
         [0.1105, 0.1167, 0.4092, 0.3401]],

        [[0.3772, 0.2479, 0.2412, 0.0046],
         [0.8316, 0.8350, 0.4125, 0.5759],
         [0.0096, 0.6448, 0.9033, 0.0755]]])

In [22]:
t1 = torch.softmax(t, dim=2)
print(t1)
t1.shape

tensor([[[0.2586, 0.1435, 0.2422, 0.3557],
         [0.2103, 0.3908, 0.1773, 0.2215],
         [0.2168, 0.2182, 0.2923, 0.2728]],

        [[0.2906, 0.2554, 0.2537, 0.2002],
         [0.2911, 0.2921, 0.1914, 0.2254],
         [0.1563, 0.2949, 0.3819, 0.1669]]])


torch.Size([2, 3, 4])

In [27]:
t2 = torch.randint(0, 4, (2, 3, 1))
t2

tensor([[[1],
         [1],
         [3]],

        [[2],
         [2],
         [1]]])

In [28]:
torch.gather(t1, dim=2, index=t2)

tensor([[[0.1435],
         [0.3908],
         [0.2728]],

        [[0.2537],
         [0.1914],
         [0.2949]]])