In [2]:
%load_ext autoreload
%autoreload 2

In [7]:
import os
from pathlib import Path
import sys
from typing import Optional, List, Dict, Any, Tuple
if '..' not in sys.path: sys.path.append('..')

from dataclasses import dataclass
from datasets import load_dataset
from datasets.arrow_dataset import Dataset
import numpy as np
from matplotlib import pyplot as plt
from pydantic_yaml import parse_yaml_file_as
import torch
from torch import nn, dist
import torch.nn.functional as F
from transformers import GPT2Tokenizer, AddedToken, PreTrainedTokenizer, AutoTokenizer, BatchEncoding

from mllm.data.wiki.dswiki import WikiDsLoader
from mllm.data.utils import RandomInputTokenizer, RandomInputTokenizerV2, TokensSubset, TokensSubsetV2, tokens_subsets_to_tensors, tokens_subsets_v2_to_tensors
from mllm.exp.args import ENCDEC_GRAPH_BERT_MODEL_CFG_FNAME
from mllm.model.encdec_ranker_hg import EncdecGraphBert
from mllm.config.model import EncdecGraphBertCfg
from mllm.train.encdec_graph_bert import MaskedCiteDataset, create_masked_cite_dataloader, load_split_wiki_dataset
from mllm.model.losses import CosLR2Loss, CosLR2LossType



In [10]:
# DATA_PATH = Path(os.path.expandvars('$HOME')) / 'data'
DATA_PATH = Path('Q:/data')
# WIKI_DS_NAME = '20200501.en'
WIKI_DS_NAME = '20220301.en'

TRAIN_ENCDEC_GRAPH_BERT_PATH = DATA_PATH / 'train_mllm_encdec_bert'
encdec_subdir = 'encdecgraphbert-20260213_121906'

encdec_train_path = TRAIN_ENCDEC_GRAPH_BERT_PATH / encdec_subdir
encdec_snapshot_fpath = encdec_train_path / 'best.pth'
encdec_graph_model_cfg_fpath = encdec_train_path / ENCDEC_GRAPH_BERT_MODEL_CFG_FNAME

device_name = 'cpu'
# device_name = 'cuda'

device = torch.device(device_name)
print(device)

cpu


## Wikipeida dataset loading

In [11]:
# dss = load_dataset('wikipedia', WIKI_DS_NAME, beam_runner='DirectRunner', cache_dir=str(DATA_PATH))
dss = load_dataset('wikipedia', WIKI_DS_NAME, cache_dir=str(DATA_PATH), trust_remote_code=True)
ds: Dataset = dss['train']
n_docs = len(ds)
print(f'Wikipedia {WIKI_DS_NAME} docs: {n_docs}')

Loading dataset shards:   0%|          | 0/41 [00:00<?, ?it/s]

Wikipedia 20220301.en docs: 6458670


### Masked dataset loading

In [12]:
tkz = AutoTokenizer.from_pretrained('bert-base-uncased')
inp_len = 128
n_special_toks = 3
mask_cfg = None
ds_cite = MaskedCiteDataset(ds, tkz, max_seq_len=inp_len, n_special_toks=n_special_toks, mask_cfg=mask_cfg, device=device)

### Inspect a masked dataset batch samples

In [6]:
batch_size = 5
inds = np.arange(batch_size)
inds = inds.tolist()
batch = ds_cite.get_batch(inds)

Token indices sequence length is longer than the specified maximum sequence length for this model (8349 > 512). Running this sequence through the model will result in indexing errors


In [7]:
print(tkz)

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


In [8]:
print(f'inp_toks: {batch.inp_toks.shape}. inp_attn_mask: {batch.inp_att_mask.shape}. first: {batch.inp_toks[0, 0]}. last: {batch.inp_toks[0, -1]}.')
print(f'prompts_toks: {batch.prompts_toks.shape}. prompts_attn_mask: {batch.prompts_att_mask.shape}. first: {batch.prompts_toks[0, 0]}. last: {batch.prompts_toks[0, -1]}.')


inp_toks: torch.Size([5, 128]). inp_attn_mask: torch.Size([5, 128]). first: 101. last: 102.
prompts_toks: torch.Size([5, 27]). prompts_attn_mask: torch.Size([5, 27]). first: 21893. last: 1012.


In [9]:
print(tkz.decode(batch.inp_toks[0].cpu().numpy()))
print(batch.inp_toks[0])

[CLS] between the two. anarchist tactics have shifted during the course of the last century. anarchists during the early 20th century focused more on strikes and militancy while contemporary anarchists use a broader array of approaches. classical era tactics discreet chandlerzzy during the classical era, anarchists had a militant tendency. not only did they confront state armed forces, as in spain and ukraine, but some of them also employed terrorism as propaganda of the deed. assassination attempts were carried out against heads of state, some oswald suspicious turns of which were successful. anarchists also took part in revolutions. many anarchists, especially the galleanists, believed [SEP]
tensor([  101,  2090,  1996,  2048,  1012, 18448,  9887,  2031,  5429,  2076,
         1996,  2607,  1997,  1996,  2197,  2301,  1012, 18448,  2015,  2076,
         1996,  2220,  3983,  2301,  4208,  2062,  2006,  9326,  1998, 23689,
        25451,  5666,  2096,  3824, 18448,  2015,  2224,  1037,

In [22]:
print(torch.all(batch.inp_toks == batch.inp_masked_toks))

tensor(True)


In [10]:
print(tkz.decode(batch.prompts_toks[0].cpu().numpy()))
print(batch.prompts_toks[0])

cite tag begin : " discreet chandlerzzy ". cite tag end : " oswald suspicious turns ". produce whole text containing these tags.
tensor([21893,  6415,  4088,  1024,  1000, 29321, 13814, 28753,  1000,  1012,
        21893,  6415,  2203,  1024,  1000, 17411, 10027,  4332,  1000,  1012,
         3965,  2878,  3793,  4820,  2122, 22073,  1012])


In [12]:
print(batch.cites_toks[0])

tensor([ 2076,  1996,  4556,  3690,  1010, 18448,  2015,  2018,  1037, 16830,
        11765,  1012,  2025,  2069,  2106,  2027, 14323,  2110,  4273,  2749,
         1010,  2004,  1999,  3577,  1998,  5924,  1010,  2021,  2070,  1997,
         2068,  2036,  4846, 10130,  2004, 10398,  1997,  1996, 15046,  1012,
        10102,  4740,  2020,  3344,  2041,  2114,  4641,  1997,  2110,  1010,
         2070,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0])


## Model loading and inference

In [13]:
model_cfg = parse_yaml_file_as(EncdecGraphBertCfg, encdec_graph_model_cfg_fpath)
chkpt = torch.load(encdec_snapshot_fpath, map_location=device)
model = EncdecGraphBert(model_cfg, tkz).to(device)
strict = True
# strict = False
model.load_pretrained(chkpt)
del chkpt
model.eval()
None

`torch_dtype` is deprecated! Use `dtype` instead!


### Inference

In [14]:
batch_off = 0
batch_size = 5
inds = np.arange(batch_size) + batch_off
inds = inds.tolist()
batch = ds_cite.get_batch(inds)

Token indices sequence length is longer than the specified maximum sequence length for this model (8349 > 512). Running this sequence through the model will result in indexing errors


In [15]:
loss_dict, dec_logits = model.run_on_text_citation(batch)
print(loss_dict)

{'cite_loss': tensor([4.6267], grad_fn=<MulBackward0>), 'cite_reg_toks_loss': tensor([5.0894], grad_fn=<MulBackward0>), 'cite_spc_toks_loss': tensor([8.3447e-06], grad_fn=<MulBackward0>), 'emb_loss': tensor(0.0773, grad_fn=<MulBackward0>), 'emb_cos_loss': tensor(0.0198, grad_fn=<MeanBackward0>), 'emb_lr2_loss': tensor(0.1347, grad_fn=<MeanBackward0>), 'input_loss': tensor([0.4305], grad_fn=<MulBackward0>), 'input_reg_toks_loss': tensor([0.4736], grad_fn=<MulBackward0>), 'input_spc_toks_loss': tensor([4.8876e-07], grad_fn=<MulBackward0>), 'loss': tensor([1.7115], grad_fn=<DivBackward0>)}


In [16]:
logits = dec_logits.detach().numpy()
logits.shape

(5, 128, 30522)

In [17]:
probs_pred = torch.softmax(dec_logits, dim=-1)
print(probs_pred.shape)
docs_toks_out = torch.argmax(probs_pred, dim=-1)
docs_toks_out = docs_toks_out.detach().numpy()
print(docs_toks_out.shape)

torch.Size([5, 128, 30522])
(5, 128)


In [18]:
for i in range(batch_size):
    print(f'=== {i} ===')
    print('inp:')
    print(tkz.decode(batch.inp_toks[i].cpu().numpy()))
    print('pred:')
    print(tkz.decode(docs_toks_out[i]))

=== 0 ===
inp:
[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped with moravian invites geometridae collectivism. anarcho - communists, who drew inspiration from the 1871 paris commune, advocated for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spread all over the world. it was a notable feature of the international syndicalism borrowedظ rpm movement. in china, small groups of students imported the humanistic pro - science version of anarcho - communism. tokyo was a hotspot for [SEP]
pred:
[CLS]. he the the of of the brain and the,, the and andist, to to,, and a a a a to to... the socialism of anarchists, to to the the -,,, and by the the,, the acomper.. the ' s effects. is a result of the -, the,, to effect the the the genes. see is.. notable topics that the to to to questions to to the activities in the union of different and of and to toize to no

## Decoding embeddings with slight variation

In [19]:
text = tkz.decode(batch.inp_toks[0].cpu().numpy())
print(text)

[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped with moravian invites geometridae collectivism. anarcho - communists, who drew inspiration from the 1871 paris commune, advocated for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spread all over the world. it was a notable feature of the international syndicalism borrowedظ rpm movement. in china, small groups of students imported the humanistic pro - science version of anarcho - communism. tokyo was a hotspot for [SEP]


In [20]:
inp_enc_embs = model.run_enc(batch.inp_toks, batch.inp_att_mask)
print(inp_enc_embs.shape)
inp_enc_embs = inp_enc_embs[:, 0]
inp_logits = model.dec(inp_enc_embs)
print(inp_logits.shape)
inp_toks_out = torch.argmax(inp_logits, dim=-1)
inp_toks_out = inp_toks_out.detach().numpy()
print(inp_toks_out.shape)

torch.Size([5, 128, 768])
torch.Size([5, 128, 30522])
(5, 128)


In [21]:
for i in range(batch_size):
    print(f'=== {i} ===')
    print('inp:')
    print(tkz.decode(batch.inp_toks[i].cpu().numpy()))
    print('pred:')
    print(tkz.decode(inp_toks_out[i]))

=== 0 ===
inp:
[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped with moravian invites geometridae collectivism. anarcho - communists, who drew inspiration from the 1871 paris commune, advocated for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spread all over the world. it was a notable feature of the international syndicalism borrowedظ rpm movement. in china, small groups of students imported the humanistic pro - science version of anarcho - communism. tokyo was a hotspot for [SEP]
pred:
[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped more moravian confront rutgers collectivism. anarcho - communism, who drew inspiration from the 1871 paris affair, credited for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spr

In [22]:
inp_embs = inp_enc_embs.cpu().detach().numpy()
print('inp_embs shape:', inp_embs.shape, 'min:', inp_embs.min(), 'max:', inp_embs.max(), 'mean:', inp_embs.mean(), 'std:', inp_embs.std())

inp_embs shape: (5, 768) min: -1.7727402 max: 0.06982117 mean: -0.0016822703 std: 0.06673085


In [23]:
emb_loss_fn = CosLR2Loss(lr_type=CosLR2LossType.L2)

In [24]:
# add small noise to inp_enc_embs and run inference again
noise = torch.randn_like(inp_enc_embs) * 1e-2
inp_enc_embs_noisy = inp_enc_embs + noise
inp_logits_noisy = model.dec(inp_enc_embs_noisy)
inp_toks_out_noisy = torch.argmax(inp_logits_noisy, dim=-1)
inp_toks_out_noisy = inp_toks_out_noisy.detach().numpy()
print(inp_toks_out_noisy.shape)

(5, 128)


In [25]:
for i in range(batch_size):
    print(f'=== {i} ===')
    print('inp:')
    print(tkz.decode(batch.inp_toks[i].cpu().numpy()))
    print('pred:')
    print(tkz.decode(inp_toks_out[i]))
    print('pred (noisy):')
    print(tkz.decode(inp_toks_out_noisy[i]))
    loss = emb_loss_fn(inp_enc_embs, inp_enc_embs_noisy)
    print(loss)

=== 0 ===
inp:
[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped with moravian invites geometridae collectivism. anarcho - communists, who drew inspiration from the 1871 paris commune, advocated for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spread all over the world. it was a notable feature of the international syndicalism borrowedظ rpm movement. in china, small groups of students imported the humanistic pro - science version of anarcho - communism. tokyo was a hotspot for [SEP]
pred:
[CLS]. under the influence of peter kropotkin, a russian philosopher and scientist, anarcho - communism overlapped more moravian confront rutgers collectivism. anarcho - communism, who drew inspiration from the 1871 paris affair, credited for free federation and for the distribution of goods according to one ' s needs. at the turn of the century, anarchism had spr